
import './globals.css'
import RootLayoutsub from "@/components/RootLayoutsub"
import StarterAnimation from "@/components/StarterAnimation";



export const metadata = {
  title: 'Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en"
    className="h-full bg-neutral-950 text-base antialiased text-neutral-100">
      <body className="flex min-h-full flex-col">
        <StarterAnimation />
      <RootLayoutsub>{children}</RootLayoutsub>
        </body>
    </html>
  )
}
